### ISSUE TITLE
Deprecated warnings with Gradle 6 

### ISSUE THREAD

**Issue by ewsachse** [zeroturnaround/gradle-jrebel-plugin#19]
I am seeing these deprecated warnings with Gradle 6.  I am using version 1.1.9 of the plugin

Property 'alwaysGenerate' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'defaultResourcesDirectory' has @Input annotation used on property of type 'File'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'defaultWebappDirectory' has @Input annotation used on property of type 'File'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'packaging' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'rebelModel' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'showGenerated' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'war' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'rebelDsl.alwaysGenerate' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'rebelDsl.packaging' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'rebelDsl.rebelXmlDirectory' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'rebelDsl.relativePath' has @Input annotation used on property of type 'File'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'rebelDsl.rootPath' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'rebelDsl.webappDirectory' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'rebelDsl.classpath.resources.$0.targetSet' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.

**Comment by MarkusPunnar** [comment]
Hello!

Thank you for the issue report. I am informing you that we have released a new version 1.1.10 of the plugin which will not show these warning when running the generateRebel task.

**Comment by ewsachse** [comment]
I updated to the new version, and most of the warnings went away.  However, I still see this one when I run this gradle command

gradlew build --warning-mode all

> Task :my-project:generateRebel UP-TO-DATE
Property 'rebelDsl.classpath.resources.$0.targetSet' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.


We do not do anything complicated with the plugin.  We just add it as a dependency to the jar task like this

jar.dependsOn(generateRebel)

We configure it in the build.gradle like this

    rebel {
        showGenerated = false
        
        classpath {
            // don't add the default classes target directory
            omitDefaultClassesDir = true
        
            // don't add the default resources directory
            omitDefaultResourcesDir = true
        
            resource {
                directory = "${projectDir}/bin/main"
			}
        }
    }

**Comment by ewsachse** [comment]
I tried upgrading to Gradle 7.0, and now I get this error from gradle

`
> Task :my-project:generateRebel FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':my-project:generateRebel' (type 'IncrementalRebelGenerateTask').
  - Type 'IncrementalRebelGenerateTask' property 'rebelDsl.classpath.resources.$0.targetSet' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`

**Comment by halfninja** [comment]
Looks like commit 617a2ecee61a07aaada3a4e2ad803766ab745148 aims to fix this

**Comment by akuusik-perforce** [comment]
Was fixed in commit [617a2ec](https://github.com/zeroturnaround/gradle-jrebel-plugin/commit/617a2ecee61a07aaada3a4e2ad803766ab745148)
